# Generated by Django 5.2 on 2026-05-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='logo',
            field=models.URLField(),
        ),
    ]
