# Generated by Django 5.2 on 2026-05-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_track_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='logo',
            field=models.URLField(default='https://res.cloudinary.com/diadkkzve/image/upload/v1778875753/Screenshot_2026-05-15_230827_jdc4yb.png'),
        ),
    ]
