# Generated by Django 5.2 on 2026-05-28 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_challenge_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='challenge',
        ),
        migrations.AddField(
            model_name='submission',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='App.challenge'),
        ),
    ]
